name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@lxd_controller_test
    secrets: inherit
    with:
      trivy-image-config: "trivy.yaml"
      provider: lxd
